---
- hosts: all
  become_user: root

  vars:
          ntp_server1: ntp.t-2.net

  tasks:
          - name: install chrony ntp client package
            yum:
                    name=chrony
                    state=present
            tags: install_chronyd,start_chronyd

          - name: deploy ntp.conf file to the client
            template:
                    src=templates/ntp.j2
                    dest=/etc/chrony.conf
                    owner=root
                    group=root
                    mode=0644
                    backup=yes
            notify: start_restart_ntp_client
            tags: copy_ntp_conf,start_ntp
          
          - name: Ensure that chrony is started and enabled on boot
            tags: chrony
            service:
                    enabled: yes
                    name: chronyd
                    state: started

  handlers:

          - name: start_restart_ntp_client
            service:
                    name=chronyd
                    state=restarted
                    enabled=yes
